name: Update Documentation
run-name: 🚀 Update /docs and README.md

on:
  push:
    branches:
      - test

jobs:
  update-documentation:
    uses: leowajda/eureka-scraper/.github/workflows/update-documentation.yml@master
    with:
      path-filter: 'src/main/**/*.java'