name: Update Documentation
run-name: 🚀 Update /docs and README.md

on:
  push:
    branches:
      - master

jobs:
  update-documentation:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: leowajda/eureka-scraper/.github/workflows/update-documentation.yml@master
        with:
          path-filter: 'src/main/**/*.java'