name: Update Documentation
run-name: 🚀 Update /docs and README.md

on:
  push:
    branches:
      - test

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  update-documentation:
    uses: leowajda/eureka-scraper/.github/workflows/update-documentation.yml@master
    with:
      path-filter: 'src/main/**/*.java'