name: Update Documentation
run-name: 🚀 Update /docs and README.md

on:
  push:
    branches:
      - master

jobs:
  checkout:
    uses: actions/checkout@v3

  update-documentation:
    uses: leowajda/eureka-scraper/.github/workflows/update-documentation.yml@master
    with:
      path-filter: 'src/main/**/*.java'